import Head from 'next/head'
import Nav from '../components/Nav'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { MDXProvider } from '@mdx-js/react'
import Button from '../components/Button'

const Code = (p) => <code className={styles.inlineCode} {...p} />
const Index = () => (
  <div className={styles.container}>
    <ViewSource pathname="pages/index.js" />
    <div className={styles.card}>
      <h1>Image Component with Next.js</h1>
      <p>
        This page demonstrates the usage of the{' '}
        <a href="https://nextjs.org/docs/api-reference/next/image">
          next/image
        </a>{' '}
        component with live examples.
      </p>
      <p>
        This component is designed to{' '}
        <a href="https://nextjs.org/docs/basic-features/image-optimization">
          automatically optimize
        </a>{' '}
        images on-demand as the browser requests them.
      </p>
      <hr className={styles.hr} />
      <h2 id="layout">Layout</h2>
      <p>
        The <Code>layout</Code> property tells the image to respond differently
        depending on the device size or the container size.
      </p>
      <p>
        Select a layout below and try resizing the window or rotating your
        device to see how the image reacts.
      </p>
      <ul>
        <li>
          <Link href="/layout-intrinsic">
            <a>layout="intrinsic"</a>
          </Link>
        </li>
        <li>
          <Link href="/layout-responsive">
            <a>layout="responsive"</a>
          </Link>
        </li>
        <li>
          <Link href="/layout-fixed">
            <a>layout="fixed"</a>
          </Link>
        </li>
        <li>
          <Link href="/layout-fill">
            <a>layout="fill"</a>
          </Link>
        </li>
        <li>
          <Link href="/background">
            <a>background demo</a>
          </Link>
        </li>
      </ul>
      <hr className={styles.hr} />
      <h2 id="placeholder">Placeholder</h2>
      <p>
        The <Code>placeholder</Code> property tells the image what to do while
        loading.
      </p>
      <p>
        You can optionally enable a blur-up placeholder while the high
        resolution image loads.
      </p>
      <p>
        Try it out below (you may need to disable cache in dev tools to see the
        effect if you already visited):
      </p>
      <ul>
        <li>
          <Link href="/placeholder">
            <a>placeholder="blur"</a>
          </Link>
        </li>
        <li>
          <Link href="/shimmer">
            <a>placeholder="blur" with animated shimmer blurDataURL</a>
          </Link>
        </li>
        <li>
          <Link href="/color">
            <a>placeholder="blur" with solid color blurDataURL</a>
          </Link>
        </li>
      </ul>
      <hr className={styles.hr} />
      <h2 id="internal">Internal Image</h2>
      <p>
        The following is an example of a reference to an internal image from the{' '}
        <Code>public</Code> directory.
      </p>
      <p>
        This image is intentionally large so you have to scroll down to the next
        image.
      </p>
      <Image alt="Vercel logo" src={vercel} width={1000} height={1000} />
      <hr className={styles.hr} />
      <h2 id="external">External Image</h2>
      <p>
        The following is an example of a reference to an external image at{' '}
        <Code>assets.vercel.com</Code>.
      </p>
      <p>
        External domains must be configured in <Code>next.config.js</Code> using
        the <Code>domains</Code> property.
      </p>
      <Image
        alt="Next.js logo"
        src="https://assets.vercel.com/image/upload/v1538361091/repositories/next-js/next-js-bg.png"
        width={1200}
        height={400}
      />
      <hr className={styles.hr} />
      <h2 id="more">Learn More</h2>
      <p>
        You can optionally configure a cloud provider, device sizes, and more!
      </p>
      <p>
        Checkout the{' '}
        <a href="https://nextjs.org/docs/basic-features/image-optimization">
          Image Optimization documentation
        </a>{' '}
        to learn more.
      </p>
    </div>
  </div>


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.icon" />
        
        
       <div className={styles.description}>{' '}<code className={styles.code}>👏 Welcome to RunAsh.Live</code></div>
      
        <div className={styles.centre}>

        <nav>
          <ul className={styles.list}>
            <li>
             <Link href="/about">
               <a>About</a>
             </Link>
            </li>
            <li>
             <Link href="/buyer">
               <a>Buyer</a>
            </Link>
           </li>
           <li>
             <Link href="/faq">
               <a>Faq</a>
             </Link>
           </li>
           <li>
             <Link href="/support">
               <a>Support</a>
             </Link>
           </li>
           <li>
             <Link href="/legal">
               <a>Legal</a>
             </Link>
           </li>
           <li>
             <Link href="/pricing">
               <a>Pricing</a>
             </Link>
           </li>
           <li>
             <Link href="/seller">
               <a>Seller</a>
             </Link> 
           </li>
           <li>
             <Link href="/blog">
               <a>Blog</a>
             </Link>
           </li>
           <li>
             <Link href="/contact">
               <a>Contact</a>
             </Link>
           </li>
           <li>
             <Link href="/my/mdx/pages">
               <a>MdX</a>
             </Link>
           </li>
          </ul>
         </nav>
         </div> 



  
    

    <h5 className={styles.description}>
    Give your store a<br /> real experience <br />on a complete digitization</h5>
    
  
      <Image
        src="/Next.js logo"
        alt="Picture of the author"
        width={100}
        height={100}
      />
      
    <Image
        alt="Next.js logo"
        src="https://assets.vercel.com/image/upload/v1538361091/repositories/next-js/next-js-bg.png"
        width={100}
        height={100}
      />

    

        
    
        
        <div className={styles.description}>{' '}<code className={styles.code}>📽️Go live on RunAsh </code></div>   
        <h5 className={styles.description}>Where the retailers <br />Build own made<br />Live streaming store</h5>
       
    </Head>

       
        <main className={styles.main}>
        <h1 className={styles.title}>
          Live retail <a href="https://">streaming</a>
        </h1>
        
        <p className={styles.description}>
          Get started by {' '}
          <code className={styles.code}>Live stream</code>
        </p>
        <p className={styles.card}>Build the next-generation and the future of e-commerce 🚀</p>
        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>🛒Real Selling &rarr;</h2>
            <p>Where retailers can meet to buyers & demonstrate their products </p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>🛍️ Real Shopping &rarr;</h2>
            <p>Where buyers can meet to sellers & shopping organic products  </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>🧑‍💻 Remote job &rarr;</h2>
            <p>Find the best startup jobs,curated by runash remote team</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>🧑‍🤝‍🧑 Influencer &rarr;</h2>
            <p>
              Live influencer community here you can support businesses 
            </p>
          </a>

          <a
            href="https://about"
            className={styles.card}
          >
            <h2>🎓 About RunAsh &rarr;</h2>
            <p>
              A live retail streaming hybrid marketplace  for retailing
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>🧗Live support &rarr;</h2>
            <p>
              24 x 7 x 365 day live support on runash  executive
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>🙋 Live video chat &rarr;</h2>
            <p>
              Follow and get started live real chatting </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>📽️ Live stream &rarr;</h2>
            <p>
              Schedule a live streaming free 
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>📺 Live watch  &rarr;</h2>
            <p>
              Watched live on demand  streaming  free
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>🥳 Own experience  &rarr;</h2>
            <p>
              Traditional own-made real experience   
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>🌈 Diffserve &rarr;</h2>
            <p>
              The promise of high quality live streaming 
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>📝 How it work &rarr;</h2>
            <p>
              When you go live to schedule a live stream
            </p>
          </a>
        </div>
        <div>
        <p className={styles.description}>
          Backed by{' '}
          <code className={styles.code}>Open Source</code>
        </p>
        
       <p className={styles.card}>Get your valuable feedback  ✨
       <a href="https://Google.form.com"></a></p>

      </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://runash.in"
          target="_blank"
          rel="noopener noreferrer"
        >
            MIT GitHub {' '}
          <span className={styles.logo}>
            <Image src="vercel.svg" alt="" width={72} height={16} />
          </span>
        </a>
      

<footer className={styles.subfooter}>Copyright © RunAsh 2022. All rights reserved.</footer>
    <footerGroup className={styles.footerGroup}>Company
      <a href="#">Home</a>
      <a href="#">About</a>
    </footerGroup>

    <footerGroup className={styles.footerGroup}>Solution
      <a href="#">Pricing</a>
      <a href="#">FAQ</a>
    </footerGroup>

    <footerGroup className={styles.footerGroup}>More
      <a href="#">Docs</a>
      <a href="#">Guides</a>
    </footerGroup>

    <footerGroup className={styles.footerGroup}>Legal
      <a href="#">OOS</a>
      <a href="#">Live</a>
    </footerGroup>
</footer>




    </div>
  )
}
